version = 1

test_patterns = [
    "tests/**",
    "test_*.py"
]

exclude_patterns = [
    "docs/**",
    ":!:*.md",
    "examples/**",

]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
