shared_data_params: #Common parameters for train and validation data
 path: ./dataset/train
 image_col: id
 label_cols: label
 extension: .png
 convert_mode: RGB

callbacks:
 early_stopping:
  _target_: torchflare.callbacks.EarlyStopping
  monitor: accuracy
  patience: 5
  mode: max

 model_checkpoint:
  _target_: torchflare.callbacks.ModelCheckpoint
  monitor: accuracy
  mode: max

 scheduler:
  _target_: torchflare.callbacks.ReduceLROnPlateau
  patience: 2
  mode: max

metric:
 _target_: torchflare.metrics.Accuracy
 num_classes: 10
 multilabel: False

experiment:
 constant_params:
  num_epochs: 2
  fp16: True
  device: cuda
  seed: 42

 compile_params:
  optimizer: Adam
  optimizer_params:
   lr: 3e-4
  criterion: cross_entropy
  main_metric: accuracy
